# Generated by Django 3.0.5 on 2025-02-03 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0007_auto_20250203_1355'),
        ('sales', '0004_auto_20190911_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stocks.Product'),
        ),
    ]
